export const dataProducts = [
    {
        id: 1,
        title: '7 thuốc sắt cho mẹ bầu dễ hấp thu, không bị nóng',
        content:
            'Trong quá trình mang thai , mẹ bầu cần lưu ý bổ sung sắt đầy đủ để tránh tình trạng thiếu máu, mệt mỏi hay ảnh hưởng đến sự phát triển của thai nhi trong bụng. Sau đây là gợi ý các loại thuốc sắt cho bà bầu tốt nhất hiện nay.  \n <b>1. Thuốc sắt dạng nước cho bà bầu Fogyma</b> \n Thuốc sắt dạng nước Fogyma được tin dùng tại nhiều bệnh viện uy tín như Từ Dũ , bệnh viện Phụ sản Trung ương, ... Với thành phần chính là Sắt III Hydroxide Polymaltose dễ hấp thu, thời gian dùng thuốc trở nên linh hoạt hơn. Mẹ bầu có thể uống trước hoặc sau bữa ăn đều được .  \n <b>Giá tham khảo:</b> Khoảng từ 150.000 ₫ 170.000 ₫ cho một hộp 4 vỉ, mỗi vỉ 5 ống 10ml .  \n <b>2. Thuốc sắt cho bà bầu Chela Ferr Forte</b> \n Được sản xuất từ đất nước Ba lan, Chela Ferr Forte luôn được đánh giá là sản phẩm cung cấp sắt và các loại vitamin cần thiết để làm giảm triệu chứng thiếu máu ở bà bầu hiệu quả . Với thiết kế dạng viên bao nén và đóng gói theo dạng vỉ tiện lợi , mẹ bầu có thể kiểm soát được liều lượng thuốc dễ dàng hơn . Mẹ bầu có thể uống 1 viên sau khi ăn sáng 1 2 tiếng .  <b>Giá tham khảo:</b> Khoảng 250.000 đồng/hộp 30 viên .  \n <b>3. Sắt nước cho bà bầu Hemopoly</b> \n Là nhãn hiệu đến từ Hàn Quốc với thành phần chính là Ferric hydroxid polymaltose complex , Hemopoly bổ sung lượng sắt vừa đủ giúp cải thiện tình trạng thiếu máu cho mẹ bầu . Đồng thời cung cấp các chất thiết yếu cho sự tăng trưởng và phát triển của thai nhi . Bên cạnh những công dụng tuyệt vời , Hemopoly cũng có thể gây ra nhiều tác dụng phụ với những mẹ bầu bị dị ứng với các thành phần của thuốc như: nổi mề đay, ngứa , da nhạy cảm ánh sáng,... Vì thế , mẹ bầu hãy tham khảo ý kiến bác sĩ trước khi sử dụng. \n <b>Giá tham khảo:</b> 360.000đ/hộp 20 ống.',
    },
    {
        id: 2,
        title: 'Bí quyết làm trắng da hiệu quả cho mẹ mang thai',
        content:
            'Để quá trình làm sáng da, trắng da an toàn và hiệu quả thì ngoài áp dựng đúng công thức , các mẹ cũng nên lưu ý một số lưu ý mẹo dưỡng trắng dưới đây. \n <b>1. Chế độ ăn uống</b> \n Phương pháp làm trắng da toàn thân cho mẹ bầu sẽ càng hiệu quả nếu được chăm sóc từ bên trong. Mẹ nên ăn nhiều rau củ, hoa quả để giúp làn da sáng mịn, chỗng lại lão hóa theo thời gian và bổ sung vitamin cho thai nhi phát triển. \n Việc cung cấp các chất dinh dưỡng từ sâu bên trong sẽ đảm bảo an toàn về sức khỏe và giúp làn da chăm sóc lâu dài thay vì những sản phẩm tác động bên ngoài \n <b>2. Vận động</b> \n Mẹ cần một cơ thể khỏe mạnh , tinh thần rạng rỡ để vừa chuẩn bị cho việc chuyển dạ , vừa cải thiện làn da mỗi ngày. Mẹ có thể tập luyện nhẹ nhàng, tham gia các khóa học yoga bầu vừa đơn giản vừa dễ dàng. \n <b>3. Uống đủ nước</b> \n Uống đủ nước sẽ vừa đảm bảo đủ ối cho bé, vừa hỗ trợ các cách làm trắng da toàn thân hiệu quả hơn. Ngoài nước lọc, các loại nước ép rau củ quả cũng là lựa chọn tốt cho mẹ mang thai \n <b>4. Cấp ẩm cho da </b> \n Muốn dưỡng trắng da toàn thân thì các mẹ bầu không nên bỏ qua cấp ẩm cho làn da thêm tươi tắn căng mọng. Nếu không dưỡng ẩm đủ thì các mặt nạ thiên nhiên hay các công dụng khác cũng không phát huy hiệu quả công dụng. Mẹ có thể sử dụng kem dưỡng thành phần từ thiên nhiên hoặc xịt khoáng để cấp đủ nước cho da. \n <b>5. Chống nắng cho da </b> \n Trong quá trình dưỡng trắng, làn da cần được bảo vệ tối đa, tránh những tác động, tiếp xúc với ánh nắng mặt trời, tia UV. Nếu không làn da mẹ bầu sẽ trở nên ngăm sạm , nám xuất hiện nhiều hơn. Vì thế hãy thoa kem chống nắng cho da mặt và da body trước khi ra ngoài mẹ nhé!',
    },
    {
        id: 3,
        title: 'Bí quyết làm trắng da hiệu quả cho mẹ mang thai',
        content:
            'Để quá trình làm sáng da, trắng da an toàn và hiệu quả thì ngoài áp dựng đúng công thức , các mẹ cũng nên lưu ý một số lưu ý mẹo dưỡng trắng dưới đây. \n <b>1. Chế độ ăn uống</b> \n Phương pháp làm trắng da toàn thân cho mẹ bầu sẽ càng hiệu quả nếu được chăm sóc từ bên trong. Mẹ nên ăn nhiều rau củ, hoa quả để giúp làn da sáng mịn, chỗng lại lão hóa theo thời gian và bổ sung vitamin cho thai nhi phát triển. \n Việc cung cấp các chất dinh dưỡng từ sâu bên trong sẽ đảm bảo an toàn về sức khỏe và giúp làn da chăm sóc lâu dài thay vì những sản phẩm tác động bên ngoài \n <b>2. Vận động</b> \n Mẹ cần một cơ thể khỏe mạnh , tinh thần rạng rỡ để vừa chuẩn bị cho việc chuyển dạ , vừa cải thiện làn da mỗi ngày. Mẹ có thể tập luyện nhẹ nhàng, tham gia các khóa học yoga bầu vừa đơn giản vừa dễ dàng. \n <b>3. Uống đủ nước</b> \n Uống đủ nước sẽ vừa đảm bảo đủ ối cho bé, vừa hỗ trợ các cách làm trắng da toàn thân hiệu quả hơn. Ngoài nước lọc, các loại nước ép rau củ quả cũng là lựa chọn tốt cho mẹ mang thai \n <b>4. Cấp ẩm cho da </b> \n Muốn dưỡng trắng da toàn thân thì các mẹ bầu không nên bỏ qua cấp ẩm cho làn da thêm tươi tắn căng mọng. Nếu không dưỡng ẩm đủ thì các mặt nạ thiên nhiên hay các công dụng khác cũng không phát huy hiệu quả công dụng. Mẹ có thể sử dụng kem dưỡng thành phần từ thiên nhiên hoặc xịt khoáng để cấp đủ nước cho da. \n <b>5. Chống nắng cho da </b> \n Trong quá trình dưỡng trắng, làn da cần được bảo vệ tối đa, tránh những tác động, tiếp xúc với ánh nắng mặt trời, tia UV. Nếu không làn da mẹ bầu sẽ trở nên ngăm sạm , nám xuất hiện nhiều hơn. Vì thế hãy thoa kem chống nắng cho da mặt và da body trước khi ra ngoài mẹ nhé!',
    },
    {
        id: 4,
        title: 'Bí quyết làm trắng da hiệu quả cho mẹ mang thai',
        content:
            'Để quá trình làm sáng da, trắng da an toàn và hiệu quả thì ngoài áp dựng đúng công thức , các mẹ cũng nên lưu ý một số lưu ý mẹo dưỡng trắng dưới đây. \n <b>1. Chế độ ăn uống</b> \n Phương pháp làm trắng da toàn thân cho mẹ bầu sẽ càng hiệu quả nếu được chăm sóc từ bên trong. Mẹ nên ăn nhiều rau củ, hoa quả để giúp làn da sáng mịn, chỗng lại lão hóa theo thời gian và bổ sung vitamin cho thai nhi phát triển. \n Việc cung cấp các chất dinh dưỡng từ sâu bên trong sẽ đảm bảo an toàn về sức khỏe và giúp làn da chăm sóc lâu dài thay vì những sản phẩm tác động bên ngoài \n <b>2. Vận động</b> \n Mẹ cần một cơ thể khỏe mạnh , tinh thần rạng rỡ để vừa chuẩn bị cho việc chuyển dạ , vừa cải thiện làn da mỗi ngày. Mẹ có thể tập luyện nhẹ nhàng, tham gia các khóa học yoga bầu vừa đơn giản vừa dễ dàng. \n <b>3. Uống đủ nước</b> \n Uống đủ nước sẽ vừa đảm bảo đủ ối cho bé, vừa hỗ trợ các cách làm trắng da toàn thân hiệu quả hơn. Ngoài nước lọc, các loại nước ép rau củ quả cũng là lựa chọn tốt cho mẹ mang thai \n <b>4. Cấp ẩm cho da </b> \n Muốn dưỡng trắng da toàn thân thì các mẹ bầu không nên bỏ qua cấp ẩm cho làn da thêm tươi tắn căng mọng. Nếu không dưỡng ẩm đủ thì các mặt nạ thiên nhiên hay các công dụng khác cũng không phát huy hiệu quả công dụng. Mẹ có thể sử dụng kem dưỡng thành phần từ thiên nhiên hoặc xịt khoáng để cấp đủ nước cho da. \n <b>5. Chống nắng cho da </b> \n Trong quá trình dưỡng trắng, làn da cần được bảo vệ tối đa, tránh những tác động, tiếp xúc với ánh nắng mặt trời, tia UV. Nếu không làn da mẹ bầu sẽ trở nên ngăm sạm , nám xuất hiện nhiều hơn. Vì thế hãy thoa kem chống nắng cho da mặt và da body trước khi ra ngoài mẹ nhé!',
    },
];
