export type RootNavigatorParamList = {
  Home: undefined,
  Premium: undefined,
  Account: undefined,
  Splash: undefined,
  Main: { screen?: string },
  Login: undefined,
  ForgotPassword: undefined,
  Register: undefined,
  VerifyOTP: user.VerifyOTPRoute,
  FetalMovement: undefined,
  PregnancyDueDateCalculator: undefined,
  PrenatalCareCheckups: undefined,
  PregnancyWeekByWeek: undefined,
  NutritionalRegimen: undefined,
  PregnancyProducts: undefined,
  RegisterSuccess: undefined,
  FetalHealth: undefined,
  HistoryFetus: undefined,
  TeachFetus: undefined,
  NutritionalRegimenDetail: undefined,
  RegisterUpdateInfo: undefined,
  FetalMovementChart: undefined,
  RoutineCheckups: undefined,
  PrenatalCareCheckupsChartMom: undefined,
  TeachFetusPhotoBaby: undefined,
  TeachFetusMusicForMom: undefined,
  TeachFetusVideoBaby: undefined,
  TeachFetusMomRead: undefined,
  TeachFetusMomReadDetail: undefined,
  Foods: undefined,
  FoodDetail: undefined,
  DishDetail: undefined,
  FetalHealthAnalysis: undefined,
  FetalHealthInfo: undefined,
  AddHistoryFetus: undefined,
  PregnancyProductsDetail1: undefined,
  PregnancyProductsDetail2: undefined,
  PregnancyProductsDetail3: undefined,
  PregnancyProductsDetail4: undefined,
  PregnancyProductsDetail5: undefined,
  PregnancyProductsDetail6: undefined,
  AddPrenatalCareCheckupsStep1: undefined,
  AddPrenatalCareCheckupsStep2: { momCheckups: user.MomCheckupsRequest },
  PrenatalCareCheckupsItemHistory: { child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse },
};
