export type RootNavigatorParamList = {
    Home: undefined,
    Premium: undefined,
    Account: undefined,
    Splash: undefined,
    Main: { screen?: string },
    Login: undefined,
    ForgotPassword: undefined,
    Register: undefined,
    VerifyOTP: user.VerifyOTPRoute,
    FetalMovement: undefined,
    PregnancyDueDateCalculator: undefined,
    PrenatalCareCheckups: undefined,
    PregnancyWeekByWeek: undefined,
    NutritionalRegimen: undefined,
    PregnancyProducts: undefined,
    RegisterSuccess: undefined,
    FetalHealth: undefined,
    HistoryFetus: undefined,
    TeachFetus: undefined,
    NutritionalRegimenDetail: undefined,
    RegisterUpdateInfo: undefined,
    FetalMovementChart: undefined,
    RoutineCheckups: undefined,
    PrenatalCareCheckupsChartMom: undefined,
    TeachFetusPhotoBaby: undefined,
    TeachFetusMusicForMom: undefined,
    TeachFetusVideoBaby: undefined,
    TeachFetusMomRead: undefined,
    TeachFetusMomReadDetail: { story: premium.Story },
    Foods: { foodCategoryRoot: food.FoodCategoryRoot },
    FoodDetail: { foodCategory: food.FoodCategory },
    DishDetail: { foodOfCategory: food.FoodCategory },
    FetalHealthAnalysis: { fromScreen: 'FETAL_HEALTH_INFO' | 'FETAL_HEALTH' },
    FetalHealthInfo: { action: 'CREATE' | 'EDIT', child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse, },
    AddHistoryFetus: { action: 'CREATE' | 'EDIT', history?: fetal.FetalHistory },
    PregnancyProductsDetail1: undefined,
    PregnancyProductsDetail2: undefined,
    PregnancyProductsDetail3: undefined,
    PregnancyProductsDetail4: undefined,
    PregnancyProductsDetail5: undefined,
    PregnancyProductsDetail6: undefined,
    AddPrenatalCareCheckupsStep1: { action: 'CREATE' | 'EDIT', child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse },
    AddPrenatalCareCheckupsStep2: { momCheckups: user.MomCheckupsRequest, action: 'CREATE' | 'EDIT', child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse },
    PrenatalCareCheckupsItemHistory: { child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse, fromScreen: 'PRENATAL_CARE_CHECKUPS' | 'FETAL_HEALTH' },
    FetalHealthChart: { child: user.CheckupsScheduleChildResponse, momId: user.CheckupsScheduleMomResponse },
    FoodSave: undefined,
    AccountInfo: undefined,
    FoodDetailSaved: { foodSave: food.FoodSave },
};
