export type RootNavigatorParamList = {
  Home: undefined,
  Premium: undefined,
  Account: undefined,
  Splash: undefined,
  Main: { screen?: string },
  Login: undefined,
  ForgotPassword: undefined,
  Register: undefined,
  VerifyOTP: User.VerifyOTPRoute,
  FetalMovement: undefined,
  PregnancyDueDateCalculator: undefined,
  PrenatalCareCheckups: undefined,
  PregnancyWeekByWeek: undefined,
  NutritionalRegimen: undefined,
  PregnancyProducts: undefined,
  RegisterSuccess: undefined,
  FetalHealth: undefined,
  HistoryFetus: undefined,
  TeachFetus: undefined,
  NutritionalRegimenDetail: undefined,
  RegisterUpdateInfo: undefined,
  FetalMovementChart: undefined,
  RoutineCheckups: undefined,
  PrenatalCareCheckupsChartMom: undefined,
  PrenatalCareCheckupsChartBaby: undefined,
  TeachFetusPhotoBaby: undefined,
  TeachFetusMusicForMom: undefined,
  TeachFetusVideoBaby: undefined,
  TeachFetusMomRead: undefined,
  TeachFetusMomReadDetail: undefined,
  Foods: undefined,
  FoodDetail: undefined,
  DishDetail: undefined,
  FetalHealthAnalysis: undefined,
  FetalHealthInfo: undefined,
  AddHistoryFetus: undefined,
};
